spring:
  data:
    mongodb:
      database: mongodb-localiza-database
      host: localhost
      port: 27017
      authentication-database: admin
      uuid-representation: standard
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher